### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by Elcid-Chawa** [FINMANAGER/FINMAMANGER#3]

**Comment by Enobong-kingsley** [comment]
### **The following are the system requirements for FinManageer on Android**

- Operating system : Android OS (above 4.1)

- Build Version : v1.0

- 1 GB RAM or more

- Internal memory 8GB

- 1920 X 1090 minimum screen resolution

**Comment by Elcid-Chawa** [comment]
Good job @Enobong-kingsley
